### ISSUE TITLE
webpack.config.js missing?

### ISSUE THREAD

**Issue by hols-zhaw** [LambdaFactory/fable-vscode-demo#2]
Hi, I get an error when trying to run `build.cmd`:

> System.Exception: dotnet command failed on fable webpack -- --config ../webpack.config.js

I tracked it down to the file `webpack.config.js` that appears to be missing. I copied and adapted this file from [ionide-vscode-fsharp](https://github.com/ionide/ionide-vscode-fsharp/blob/master/webpack.config.js) which worked fine for me. See file attached.

Thanks for the template!
[webpack.config.js.zip](https://github.com/LambdaFactory/fable-vscode-demo/files/1315616/webpack.config.js.zip)

**Comment by StachuDotNet** [comment]
will create PR in a few minutes.
